package com.asdin.test_rest.dto.report;

import lombok.*;
import java.math.BigDecimal;

/** Sold item ranking generated by a native aggregation query. */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TopItemRow {
    private Long itemId;
    private String title;
    private Long bidCount;
    private BigDecimal finalPrice;
}
